### ISSUE TITLE
Add helper for creating resources from strings

### ISSUE THREAD

**Issue by shadowhand** [http-interop/http-factory#11]
By forcing streams to be created with existing resources, (see https://github.com/http-interop/http-factory/pull/2#issuecomment-240454239), it makes the factory more difficult to use.

While I approve of the reasoning that @weierophinney makes, we should also seek to keep the barrier to entry low enough that developers do not have to learn how to create a temporary resource to use the stream factory. I think it would be worth defining a function that is included with this package to make it easier:

``` php
function get_temporary_resource(string $content) : resource
```

Usage would make calls to factories more clear:

``` php
$stream = $streamFactory->createSream(get_temporary_resource($content));
```

**Comment by shadowhand** [comment]
@weierophinney thoughts on this? Should we switch the interface back to accepting `string|resource` and add this function? I definitely see a need to resolve this, just not sure what the right way forward is.

**Comment by Nyholm** [comment]
For simplicity I like `string|resource`. But why do we need the `get_temporary_resource`? Isn't that an implementation detail in the factory implementation?

**Comment by shadowhand** [comment]
Maybe it is. My concern with having `string` is that it is ambiguous... is it a filename, or a string of content?

**Comment by Nyholm** [comment]
Let's control that in the doc block. I think it should be a string of content. That would leave opening and closing files outside of our concerns.

**Comment by weierophinney** [comment]
Multiple types are always a bit of a concern when considering arguments; the user has to read documentation in order to understand what is acceptable. I'm as guilty of this as anyone, but trying to improve my ways.

As such, I wonder if this is one place that potentially warrants two method:

``` php
createStreamFromResource($resource);
createStreamFromString($content);
```

The latter would be documented such that implementors would know they need to create a `php://memory` or `php://temp` stream with the given content and then proxy to the other method once done.

Alternately, keep the single method, and ship with the given utility for creating an in-memory/temp stream from string content.

I'd be fine with either, but I definitely think overloading the method to accept either will be problematic.

**Comment by shadowhand** [comment]
@weierophinney and now we're back to #2. 😆

**Comment by Nyholm** [comment]
Multiple functions would not make any sense. Please correct me if Im wrong but the goals of this organisation is (in no particular order):
- Figure out the best possible solution
- Adapting to current leading implementations
- Be developer friendly

These three together will make good interoperability. 

Since we cant decide on the best possible solution, lets look at the other two goals. 

---

Consider the 3 major PSR-7 implementation: Guzzle, Zend and Slim. Let's see what the implementation would look like for a StreamFactory:

``` php
// Guzzle
public function createStream($data) {
    return Psr7\stream_for($data); // Accepts both string and resource
}

// Zend
public function createStream($data) {
    return new Stream($data); // Accepts both string and resource
}

// Slim
public function createStream($data) {
    if (is_scalar($data)) {
        $stream = fopen('php://temp', 'r+');
        if ($resource !== '') {
            fwrite($stream, $data);
            fseek($stream, 0);
        }
        $data = $stream;
    }
    return new Stream($data); // Accepts only resource
}
```

As you can see. 2 of 3 implementations would have the exact same function body for `createStreamFromResource` and `createStreamFromString`. That is why I do not think we should have separate methods. 

> Alternately, keep the single method, and ship with the given utility for creating an in-memory/temp stream from string content.

As long as the utility is in a separate package I'm good. I do not like this because (1) it is an implementation, (2) it is trivial and (3) it is only needed by Slim. 

FYI: PSR-6 was shipped with some code to make implementations easier. It has barley been used/downloaded. See https://packagist.org/packages/fig/cache-util

**Comment by shadowhand** [comment]
:+1: good examples @Nyholm!

**Comment by harikt** [comment]
Diactoros accepts string in the sense filename etc. Not real string values I believe.

So `new Stream("Hello World");` will not work. Correct me if I am wrong @weierophinney .
