### ISSUE TITLE
StreamFactory without open the resource

### ISSUE THREAD

**Issue by oscarotero** [http-interop/http-factory#19]
Currently the StreamFactoryInterface has two modes:

Passing a stream resource:

``` php
$stream = $factory->createStream(fopen('php://temp'));
```

Or a string, interpreted as the stream content.

``` php
$stream = $factory->createStream('Hello world');

//so its equivalent to:
$stream = $factory->createStream(fopen('php://temp'));
$stream->write('Hello world');
```

The problem here is that in both cases the stream resource must be opened. I'd like to be more conservative here, and do not open the stream until it's completely neccesary, because sometimes the stream is not used in the request or response if the body is empty.

I propose to use, instead the file path of the stream, with an optional second argument for the opening mode:

``` php
$stream = $factory->createStream('php://temp', 'r+');
```

**Comment by mindplay-dk** [comment]
> I propose to use, instead the file path of the stream, with an optional second argument for the opening mode

I've been arguing that as well. If the arguments I can pass to `fopen()` are identical to the ones I can pass to the factory method, that also makes it easier to create a mock factory that produces memory-only streams.

I think the opposite requirement though, is you have a resource handle already open, and then what? I think we would need two factory interfaces, or else we're back to the idea of overloading a single factory interface, of which I'm not a fan.

**Comment by shadowhand** [comment]
I am against having a method that takes file paths and modes, because:
1. It only eliminates a single `fopen` call.
2. Testing all the various permutations of `$mode` is hard/impossible.
3. Attempting to define the error conditions for being unable to open the file, or being unable to write to a read-only file is a lot of extra work that has nothing to do with creating a stream.

Streams are backed by resources and represented (during output) as a string. Therefore, I think that all streams should be constructed from a resource or string. Additional stream types (callable, etc) are outside the scope of PSR-17.

**Comment by oscarotero** [comment]
Ok, I understand this. But creating a stream from a string requires to open the stream inside the factory (only to eliminate a single `write` call)  so I don't understand why this is not a problem.

**Comment by mindplay-dk** [comment]
@shadowhand I'm with @oscarotero on this one. You say you're against having a method that takes file paths and modes because it only eliminates a single `fopen()` call - well, accepting content only eliminates a single `fwrite()` call.

If you really boil this down to the essential, what we need to provide interoperability, is a factory method that constructs a `StreamInterface` for an existing `resource`. Strictly speaking, anything above that is non-essential, higher-order functionality - all of which is enabled and can be accomplished by the first interface.

Everything beyond that is in the name of _utility_ rather than _interoperability_, and in adding any such features, we're dictating architecture, burdening implementers with identical code and tests.

**Comment by mindplay-dk** [comment]
The main problem is that, once you allow _any_ scope creep beyond what's required for interoperability, there is no objective way to draw the line, only subjective opinions about additional scope and implied architecture - everything beyond the non-essential is opinion, dictating architecture.

IMO, even a small amount of that is bad.

**Comment by shadowhand** [comment]
> do not open the stream until it's completely neccesary, because sometimes the stream is not used in the request or response if the body is empty

This is way beyond the scope of the current proposal though, and is entirely up to the PSR-7 implementation. As it stands right now, I don't know of _any_ PSR-7 implementation that defers stream creation in this way. Beyond that, I don't think think there would be any benefit to doing so. An `fopen` call is extremely cheap, especially a temporary file, which exists in memory by default.

**Comment by oscarotero** [comment]
I could swear I saw it in Diactoros, but after looking again, seems I was wrong. So maybe a createStreamFromFile factory makes no sense finally.

**Comment by mindplay-dk** [comment]
> I don't think think there would be any benefit to doing so. An `fopen` call is extremely cheap

Yeah, this.

:-)
