### ISSUE TITLE
Use the correct namespace

### ISSUE THREAD

**Issue by shadowhand** [http-interop/http-factory#3]
Should we continue to use `Psr\Http` or would it be better to use `Interop\Http`?

cc @http-interop/http-factory-contributors

**Comment by harikt** [comment]
`Psr` seems not good for it can always break if someone implemented it. So I prefer not to use `Psr` until all the Fig members are ok with it :) .

**Comment by mindplay-dk** [comment]
I'd stick with the `Psr` namespace for now - the entry has already been accepted, so unless the FIG rejects the final outcome, let's leave it as is? Rename it if they reject it. Let's assume success :-)

**Comment by shadowhand** [comment]
Like `container-interop`, I would rather this package be usable before the PSR is accepted.

**Comment by mindplay-dk** [comment]
> I would rather this package be usable before the PSR is accepted

Why wouldn't it be?

What does this have to do with the namespace?

Container interop uses the `Psr` namespace in the specification - all PSRs in draft listed on the FIG home page do. I don't understand why we would plan to make a breaking change from the get-go? If the PSR does _not_ get approved, that's technically a "breaking change" and we should change the name then - if it gets approved, should that be a breaking change? It will be.

Sorry, not trying to be difficult, but I genuinely do not understand what the idea is, or why using the `Psr` namespace for something that is presently a PSR-in-draft is a problem?

**Comment by shadowhand** [comment]
There will no `1.0.0` release until PSR-17 is accepted and I'm using 0.x releases right now, which as per semver, allow for breaking changes at any time.

**Comment by mindplay-dk** [comment]
> There will no `1.0.0` release until PSR-17 is accepted and I'm using 0.x releases right now, which as per semver, allow for breaking changes at any time

Of course.

I still don't see why that's an argument for using a _likely_ wrong, temporary namespace, pending `1.0`?

Am I missing something?

**Comment by shadowhand** [comment]
> Am I missing something?

I feel like the future of FIG is a bit uncertain right now. I'd rather that this package not be tied to FIG until PSR-17 actually sees the light of day.

**Comment by mindplay-dk** [comment]
> I'd rather that this package not be tied to FIG until PSR-17 actually sees the light of day.

I have to touch on this issue again.

I'm about to release middleman 2.0 with a dependency on `http-interop/http-middleware^0.2`, and I am somewhat concerned about the implications of a potential package name-change.

If I release my package with a dependency on `http-interop/http-middleware^0.2`, and we go through more iterations of non-breaking changes, I have no problem - I will simply test with the next release.

If, on the other hand, the package-name and/or namespace changes, I will inherit these breaking changes, which will force me to release middleman 3.0, due to no real practical change, other than the change of ownership.

How committed are we to the `http-interop` vendor-name?

Will it stay?

Is there any practical reason to change it for any reason in the future?

It's my understanding that e.g. `container-interop` do not plan on changing their vendor-name if/when that gets standardized as a PSR.

I also seem to recall reading somewhere (though I can't recall where) that some members of FIG were calling for projects to generally adopt the `*-interop` vendor-name approach, perhaps due to some of the same concerns about standards/packages starting out their existence in a vacuum, then later being adopted as official recommendations.

@http-interop/http-factory-contributors @http-interop/http-middleware-contributors thoughts?

**Comment by harikt** [comment]
@mindplay-dk I would have suggested to call 0.x , but in your case you have already moved to 1.0 earlier. So go for major versions because there is no problem releasing 3.x , or 5.x :) .

**Comment by weierophinney** [comment]
> It's my understanding that e.g. container-interop do not plan on changing their vendor-name if/when that gets standardized as a PSR.

Yes and no.

They will continue to release container-interop. However, they will also release a library via FIG, and that will be the official implementation. A new version of container-interop will be released that _extends_ the interfaces from the FIG library, to allow users that already depend on container-interop to upgrade immediately, allowing their code to be used by consumers of the FIG interfaces,  and then later update their code later to use the official interfaces. We can do the same here with the http-interop project.

**Comment by mindplay-dk** [comment]
> A new version of container-interop will be released that extends the interfaces from the FIG library, to allow users that already depend on container-interop to upgrade immediately

That's a terribly confusing solution.

Packages that depend on the same thing will _appear_ to depend on two different things. You won't even be able to trace the dependencies of the package via Packagist, for example. You won't be able to explain unambiguously to someone which package you're really depending upon.

By no practical definition do the classes of one package "extend" classes of the other - so that's a patch/hack/work-around, and IMO not a pretty one.

I'd rather have to deal with the pain of deprecation and being forced to properly upgrade.

Deprecation at least makes it clear what's happening, instead of trying to hide it.

**Comment by shadowhand** [comment]
At this time, I would like to continue with 0.x releases of http-interop packages, until the PSR is fully ratified. Even once it is, I am not entirely sure that the namespace should change.
