### ISSUE TITLE
Two factories to create serverRequest

### ISSUE THREAD

**Issue by oscarotero** [http-interop/http-factory#31]
In the current version, the serverRequestFactory was splitted into two factories: `createServerRequest` and `createServerRequestFromArray`.

To me, this change is a step back, because there's no easy way to create a full serverRequest instance without post-manipulation. The commit message https://github.com/php-fig/fig-standards/pull/868/commits/31663251d3fc37653ab1441035a8ed187736b2b1 says *Creating a server request from the `$_SERVER` array or a custom request with method and URI are two different needs.* They can be different needs, but not always, and different needs do not mean different functions.

For example, in my factory https://github.com/middlewares/utils/blob/master/src/Factory.php#L146 I need to create server requests with an uri, a method and sometimes other server attributes for testing purposes (REMOTE_ADDR for ips, REQUEST_TIME_FLOAT to calculate the response duration, etc...) And to create this request, I have to use also a UriFactory because there's no easy way to create a serverRequest using just the server attributes (we need to split uri in different parts and save them as SERVER_NAME, REQUEST_URI, QUERY_STRING, etc...)

I think the previous version was better: just one factory with the same arguments than requestFactory adding the server attributes, that fits well in all needs.

**Comment by shadowhand** [comment]
The reason for the split is simple:

- `createServerRequestFromArray` create a complete server request from the `$_SERVER` array
- `createServerRequest` create a custom server request

Everything else after that point can be done by using the standard manipulation methods. Additional attributes, such as IP addresses, can be handled in this way.

**Comment by Nyholm** [comment]
Agreed. That is also why the RequestFactory and ResponseFactory creates a minimal Requests and Responses.

**Comment by oscarotero** [comment]
I think this is a bad idea for various reasons:

* To me, createServerRequestFromArray is an implementation feature. There's non unique way to create a complete server request using just an array. The existence of this issue #32 reflects this point and opens the door to different interpretations.
* Is more difficult to create a library to create instances of serverRequest using global values, because this feature is included in the factory. For example:

```php
use ServerRequestCreator\Creator;

$creator = new Creator(new PsrServerRequestFactory());

$serverRequest = $creator->fromGlobals([
    'useMethodOverride' => true,
    'useIISRewriteModule' => true
]);
```

This could be a library to interpret the global `$_SERVER` array and create a serverRequest with the extracted values. It could also include options to detect the uri and method in an advanced way, and use any ServerRequestFactory, so the result can be an instance of your favorite implementation (guzzle, diactoros, slim, etc). If the request is created with `createServerRequest`, there's no way to insert the server parameters, and if it's created with `createServerRequestFromArray`, the factory will execute unnecesary code to detect the uri and method that must be overrided by the Creator.

Frankly, I don't see any benefit in split the factory in two methods. The uri and method should not be based in the $_SERVER parameters, they are different values that represents different things (in the same way that we have the query parameters as an array in `getQueryParams()` and as a string in `getUri()->getQuery()`.

**Comment by mindplay-dk** [comment]
Can we unify these methods?

So that:

```
createServerRequest($method, $uri);
createServerRequestFromArray(array $server);
```

Becomes:

```
createServerRequest($method, $uri, array $server = []);
```

**Comment by Zegnat** [comment]
> To me, createServerRequestFromArray is an implementation feature. There's non unique way to create a complete server request using just an array. The existence of this issue #32 reflects this point and opens the door to different interpretations.

This pretty much sums up my thoughts. #32 exists because the spec will have to make it a “unique way” for things to be workable. Maybe that is the wrong solution though, and the real solution is to not even suggest there is such a thing as a ServerRequest created out of an array alone.

> The uri and method should not be based in the $_SERVER parameters, they are different values that represents different things (in the same way that we have the query parameters as an array in getQueryParams() and as a string in getUri()->getQuery().

What’s the policy here? Is a return value for `getQueryParams()` set when the factory creates a ServerRequest from `$method` and `$uri`? Should it specifically *not* extract the query from the URI? Or is this left to the implementer?

> Can we unify these methods?

:+1: The only unsettable value after instantiation is the return value for `getServerParams()`. As long as the factory offers a way to set that, everything else is covered by PSR-7 setters.

**Comment by mindplay-dk** [comment]
Okay, so, let's take it from the top.

There are two distinct use-cases: creating a server-request from the current state of globals, and creating a custom server-request.

For the custom server-request, we need to take into account the fact that there is not factory-method for server-params, so the only way to set these will be at the time of creation.

So, if we have just a single interface with a single method:

    createServerRequest($method, $uri, array $server = []);

I think this may in fact cover all the bases, because an implementation of a factory that creates a server-request from globals could simply depend on an implementation of the single factory-interface.

This way, you end up with just one factor with just one implementation for each PSR-7 package, and we're covered as far as interoperability goes.

In principle, a single package could take care of creating server-requests from globals, for *all* PSR-7 implementations - as long as they have an implementation of the above interface.

We *could* have an additional second interface to abstract from the creation of a server-request from globals:

    createServerRequestFromGlobals();

But most likely, this would be a framework-only concern, so it's probably not even really necessary?

I mean, any project will need *one* way to create the incoming server-request from globals - only frameworks and front-controllers need this functionality in the first place, so being able to swap out that implementation probably has very little value. Interoperability on this point probably doesn't have any real benefits?

**Comment by shadowhand** [comment]
```
createServerRequestFromGlobals();
```

In fact, [this used to be a thing](https://github.com/http-interop/http-factory/blob/380fd6d00139cd3ad92b32a8d63ee07eaa39dd9f/src/ServerRequestFromGlobalsFactoryInterface.php#L15) but it was removed in #23 because it was determined to be a leaky abstraction (depended on globals) and couldn't be mocked properly.

> only frameworks and front-controllers need this functionality in the first place, so being able to swap out that implementation probably has very little value. Interoperability on this point probably doesn't have any real benefits?

I disagree completely. Without having an interop for this functionality, it is impossible to transparently swap out PSR-7 implementation. [This is how it is done](https://github.com/shadowhand/mvc-example/blob/12420857c1bacbbc0e2308d90903ae07a32819c3/config/injection/http.php#L43-L45) without depending on a concrete implementation of `ServerRequest`.

**Comment by mindplay-dk** [comment]
> it was determined to be a leaky abstraction (depended on globals) and couldn't be mocked properly.

True.

> Without having an interop for this functionality, it is impossible to transparently swap out PSR-7 implementation

Well, what are you referring to now? I was only referring to creating server-request *from globals* - of course we need to be able to create a server-request.

And from what you just said about that requiring a leaky abstraction, an interface for that wouldn't help much, right?

**Comment by shadowhand** [comment]
This has been resolved in the final spec.
