### ISSUE TITLE
Create a separate package for additional streams

### ISSUE THREAD

**Issue by shadowhand** [http-interop/http-factory#4]
Would it make sense to create a `http-factory-streams` package that contains additional stream types like `CallbackStream`, etc?

Refs https://github.com/http-interop/http-factory/pull/1#issuecomment-239760194

cc @http-interop/http-factory-contributors

**Comment by harikt** [comment]
Though

``` php
namespace Psr\Http\Factory;

use Psr\Http\Message\StreamInterface;

interface StreamFactoryInterface
{
    /**
     * Create a new stream
     *
     * @return StreamInterface
     */
    public function createStream();

}
```

the interface sounds good, how are we going to tackle different implementations ?

``` php
use Zend\Diactoros\CallbackStream;

class CallbackStreamFactory implements StreamFactoryInterface
{
    public function createStream()
    {
        return new CallbackStream(); // Diactoros needs $callable, ok. So do we need to define the constructor or other methods for Streams or are we going with any other route ?
    }
}
```

Lets consider a `CallbackStreamFactory` . How are we going to pass the `callback`? Is it through constructor or setter? If it is constructor doesn't the `createStream` need to be different for different `StreamFactory` ?

I am looking at https://github.com/zendframework/zend-diactoros/blob/b4e7758556c97b5bb9a5260d898e9788ee800538/src/CallbackStream.php#L30 and https://github.com/zendframework/zend-diactoros/blob/b4e7758556c97b5bb9a5260d898e9788ee800538/src/Stream.php#L36 .

**Comment by shadowhand** [comment]
This is incorrect:

``` php
class CallbackStreamFactory implements StreamFactoryInterface { ... }
```

What I am suggesting is a separate package that provides additional interfaces for other stream types (like the ones that Diactoros) contains:

``` php
class CallbackStreamFactory implements CallbackStreamFactoryInterface { ... }
```

**Comment by harikt** [comment]
Thank you for the correction @shadowhand . In that case what is the benefit if we are making as a separate package ? Doesn't that sounds a different sort of PSR then ?

**Comment by shadowhand** [comment]
It would be a separate package because not all projects can create those kinds of streams.

**Comment by harikt** [comment]
The use of PSR is every projects which follow it should be able to provide the implementation. If it cannot let it stand different. I am against this idea for the current time.

Thank you for your time to move this forward.

**Comment by dracony** [comment]
Actually now that I had some time to look into things I think that we can't have a StreamFactoryInterface at all. Since a stream is the smallest building block of PSR-7 we have to consider it as something given by the implementation itself. 

E.g. you can't just have a StreamFactoryInterface::createStream() method, because a particular implementation may not allow for a no-argument stream. I guess the only stream factory method we could kind of force to exist is StreamFactoryInterface::createStreamFromString($string) etc. methods since it's pretty generic.

**Comment by shadowhand** [comment]
@dracony I think the only reasonable expectation we can make of every implementation is:

``` php
StreamFactoryInterface::createStream($resource)
```

Allowing a string is too ambiguous. Is it a filename or is it text or is it binary? Should it be writable? All of these questions are irrelevant if a resource is passed in.

**Comment by mindplay-dk** [comment]
> Allowing a string is too ambiguous

This closely relates to what I've been trying to say about the stream interfaces.

I think that a name like `StreamFactoryInterface::createStream()` is completely ambiguous to begin with, and no such interface should exist.

Instead, every defined interface should have one designated purpose and outcome, for example:

```
StringStreamFactoryInterface::createStreamFromString()
FileStreamFactoryInterface::createStreamFromFilename()
ResourceStreamFactoryInterface::createStreamFromResource()
```

etc.

Each has one defined input and outcome: each is a distinct type of factory producing a Stream with certain specific capabilities.

**Comment by shadowhand** [comment]
@mindplay-dk I created #14 to address your comment. It definitely feels like we're waffling on previous decisions, though it will be nice to have a good record of this.

**Comment by Nyholm** [comment]
I do not like that idea. Think of the implications. Consider the Zend implementation of a stream*factory. It would probably look like this: 

``` php
class StreamFactory implements StringStreamFactoryInterface, FileStreamFactoryInterface, ResourceStreamFactoryInterface {
```

Now consider the case of the Mailgun API client (and many more) they allow you to have a parameter with attachments that is a reference to a file. So they would need a `FileStreamFactoryInterface`. And since they also send a normal POST body they need a `StringStreamFactoryInterface`. So they need to type hint for two stream factories but they will get the same object. 

``` php
class MailgunClient {

  public function __construct(HttpClient $httpClient, StringStreamFactoryInterface $stingStream, FileStreamFactoryInterface $fileStream) {
    // $stringStream and $fileStream are references to the same obeject
  }
}
```

Also, it is not unheard of that the mailgun client should support resources. 

Splitting it up to different interfaces is a big 👎  for me.

**Comment by mindplay-dk** [comment]
> So they need to type hint for two stream factories but they will get the same object.

The point is, that's not a given - one could get either or both stream factories from the same implementation.

You're not thinking of the case where a special type of stream is introduced for special purposes - if everything is dependent on a single interface, the concept does not extend beyond anything we've defined.

You're also not thinking about the potential to add a new stream factory to the PSR itself in the future - this would be a breaking change.

You're also not thinking about testing - we don't want to have to mock six different factory methods for the purposes of testing a component that only uses one or two of those.

Those are some (but not even all) of the reasons we abide by SRP in general.

Also, your proposed implementation of a zend stream factory is speculative - if they have to break BC to support these interfaces either way, there's an equally good chance they will break up different factories into different classes, or a hierarchy of classes; either way, we're speculating.

Please don't assume that we haven't thought of the implications of both approaches - it has been discussed at length already, and we settled on this.

**Comment by Nyholm** [comment]
> You're not thinking of the case where a special type of stream is introduced for special purposes - if everything is dependent on a single interface, the concept does not extend beyond anything we've defined.

There is no special type of stream. There is just one stream in PSR-7. And PSR-7 is the communities best attempt to model HTTP. 

> You're also not thinking about the potential to add a new stream factory to the PSR itself in the future - this would be a breaking change.

That is not a valid argument. That "potential new stream factory" could be in a separate interface. That would not be a breaking change. 

> You're also not thinking about testing - we don't want to have to mock six different factory methods for the purposes of testing a component that only uses one or two of those.

Of course not, one have to respect the interface segregation principle. But I guess misunderstood my suggestion. I suggest to have one interface and method to create a stream. `StreamFactory::createStream`. When you are writing your mocks you do only have to mock one factory method.

> Those are some (but not even all) of the reasons we abide by SRP in general.

Can we (for the discussion) name that responsibility? Im my opinion it is "To create a stream". I fear over engineering. If you apply SRP everywhere and in detail you end up with classes/interfaces with only one method. 

> Please don't assume that we haven't thought of the implications of both approaches - it has been discussed at length already, and we settled on this.

I did not know. Sorry for that. Please reference me to those discussions.

**Comment by mindplay-dk** [comment]
> There is no special type of stream

Yes, there are. Even if all streams have the same interface, they do not have the same characteristics - network, memory or file-based streams have _very_ different characteristics in terms of performance, memory usage, network overhead, size limitations, and more.

> There is just one stream in PSR-7

No, there is one stream _interface_ - huge difference. There are potentially an _infinite_ variety of streams covered by PSR-7, with wildly different characteristics.

> > You're also not thinking about the potential to add a new stream factory to the PSR itself in the future - this would be a breaking change.
> 
> That is not a valid argument. That "potential new stream factory" could be in a separate interface. That would not be a breaking change.

I assumed we wanted consistency.

If we end up with one interface with many methods, and then add a new interface in the future with just one method, that's inconsistency in favor on convenience. And that convenience doesn't even last - unless the single interface hampers the addition of a supplemental single-method interface, which hampers further development of the standard, all of which are undesirable, in my point of view.

> > Those are some (but not even all) of the reasons we abide by SRP in general.
> 
> Can we (for the discussion) name that responsibility? Im my opinion it is "To create a stream"

Creating what type of stream, and from what?

If I'm going to stream a very large file, I'm going to need a temporary/buffered stream, for example - that's a very different type of stream from a memory-based stream I need to output a few K of JSON or HTML.

You can't just have one interface, because only the client (e.g. middleware component) can know the purpose and requirements it has for the type of stream it needs to create.

**Comment by shadowhand** [comment]
As per discussion on #2, #4, and #14, stream factory will support `string|resource` and will not include support for other types. Additional types of streams (callback, file stream, etc) are outside the scope of this package.

A future PSR could be created to define additional stream factories if deemed necessary by the community. Anyone using those types of streams is likely already coupled to a specific implementation (eg: Guzzle) and would not have need for HTTP Factory.

**Comment by mindplay-dk** [comment]
> Additional types of streams (callback, file stream, etc) are outside the scope of this package.

Aren't file streams common enough that we should cover that? Sending a file seems like a common case.

For callbacks and other exotic stream types, interop is probably not important - for those, one will almost certainly have to select a very specific implementation, or possibly write or extend another.

**Comment by shadowhand** [comment]
@mindplay-dk as I said on #16, using a file for a stream is trivial:

``` php
$factory->createStream(fopen($file, 'r'));
```

Having to add a `mode` parameter would make the signature inconsistent when passing an existing resource:

``` php
$factory->createStream($resource, 'r');
```

In this latter example, what is the expected outcome if the given mode (`r`) doesn't match the currently opened resource? This is undefined behavior and we shouldn't design an interface that allows it.

**Comment by Nyholm** [comment]
You are correct @mindplay-dk I was only considering the PSR7 stream **interface**. There is many type of streams. But I do not think we should be more specific when defining a stream than PSR7. 

Thank you for a good discussion.
